TARGET_CLASSES = ['AMERICAN SNOOT', 'CRIMSON PATCH', 'MALACHITE', 'GOLD BANDED', 'WOOD SATYR']

IMAGE_SIZE = 64
BATCH_SIZE = 32

IMAGES_TO_GENERATE = [46, 47, 47, 47, 48]

GENERATE_COUNT_MAP = dict(zip(range(len(TARGET_CLASSES)), IMAGES_TO_GENERATE))